// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9PgYjAiwnyvf_6wSL2Js2PRK0zW0cGc8',
    appId: '1:954888224491:web:f51ce9570fb5bd97c488ae',
    messagingSenderId: '954888224491',
    projectId: 'ace-time-mike',
    authDomain: 'ace-time-mike.firebaseapp.com',
    storageBucket: 'ace-time-mike.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDchyN_A1XGs7idqCKfjy0QggGrM-qh75g',
    appId: '1:954888224491:android:f4eede0883a8fc93c488ae',
    messagingSenderId: '954888224491',
    projectId: 'ace-time-mike',
    storageBucket: 'ace-time-mike.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvEJ9X6VxPBKP-eeu6ZaTOhLgLUoRevJY',
    appId: '1:954888224491:ios:7f1aca4555826d12c488ae',
    messagingSenderId: '954888224491',
    projectId: 'ace-time-mike',
    storageBucket: 'ace-time-mike.firebasestorage.app',
    iosBundleId: 'com.example.aceTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvEJ9X6VxPBKP-eeu6ZaTOhLgLUoRevJY',
    appId: '1:954888224491:ios:7f1aca4555826d12c488ae',
    messagingSenderId: '954888224491',
    projectId: 'ace-time-mike',
    storageBucket: 'ace-time-mike.firebasestorage.app',
    iosBundleId: 'com.example.aceTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9PgYjAiwnyvf_6wSL2Js2PRK0zW0cGc8',
    appId: '1:954888224491:web:b8eef9677589ff32c488ae',
    messagingSenderId: '954888224491',
    projectId: 'ace-time-mike',
    authDomain: 'ace-time-mike.firebaseapp.com',
    storageBucket: 'ace-time-mike.firebasestorage.app',
  );
}
